name: ftd-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.12

  # Core data analysis libraries
  - pandas>=2.0.0
  - numpy>=1.24.0

  # Prediction
  - scikit-learn

  # Data visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly

  # Jupyter notebook support
  - jupyter>=1.0.0
  - ipykernel>=6.20.0

  # Utilities
  - python-dateutil>=2.8.0
  - pip

  - pip:
    - currencyconverter